# Generated by Django 3.1.1 on 2020-09-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200918_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='def_av.jpg', upload_to='profile_pics'),
        ),
    ]
